version: '3.9'

services:
  web:
    build:
      context: ./myviews
      dockerfile: Dockerfile.prod
    command: gunicorn myviews.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - static_volume:/home/myviews/web/staticfiles
      - media_volume:/home/myviews/web/mediafiles
    expose:
      - 8080
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/myviews/web/staticfiles
      - media_volume:/home/myviews/web/mediafiles
    ports:
      - 3000:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
