version: '3.9'

services:
  web:
    build: ./myviews
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./myviews/:/usr/src/myviews/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
    
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lumkile
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=myviews_dev

volumes:
  postgres_data:
